######################################################################
# Automatically generated by qmake (3.0) pon. gru 26 02:56:54 2016
######################################################################

TEMPLATE = app
TARGET = pong
NCLUDEPATH += /usr/include/GL
LIBPATH += /usr/lib
LIBS += -lglut -lGL -lGLU
CONFIG += c++11


# Input
HEADERS += Prostokat.h sKolor.h \
    ball.h
SOURCES += main.cpp Prostokat.cpp \
    ball.cpp
